#!/bin/bash

# Check validity of arguments
if [[ $# -lt 1 ]]; then
	echo "Missing argument! Example: ibash FILE_NAME"
	exit
elif [[ $# -gt 1 ]]; then
	echo "Too many arguments, ibash only accepts 1 argument! Example: ibash FILE_NAME"
	exit
fi

file_name="$1"

# Check if file exists

if [[ -f "$file_name" ]]; then
	read -p "File exists. Overwrite? (y/n): " choice
	
	# If anything other than 'y' is given, it will exit
	if [[ $choice != "y" ]]; then
		echo "Action stopped."
		exit
	fi
fi

touch "$file_name"

chmod +x "$file_name"

echo "#!/bin/bash" > "$file_name"
